### ISSUE TITLE
Can't edit members

### ISSUE THREAD

**Issue by asepulcri** [thor-it/Teamsite-Public#20]
After clicking on edit member the page just loads indefinitely

**Comment by davidzwa** [comment]
Thanks for the report @asepulcri. It is a known bug.

I will push a fix tonight!

**Comment by davidzwa** [comment]
The fix is not live yet due to possible changes in the GMail functionality. @asepulcri this will be tested this weekend and the fix will be pushed asap.

Sorry for the delay
